name: Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask

      - name: Set up environment variables
        run: |
          echo "ALLOWED_EXTENSIONS=${{ secrets.ALLOWED_EXTENSIONS }}" >> .env
          echo "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}" >> .env\
          echo "FLASK_DEBUG=${{ secrets.FLASK_DEBUG }}" >> .env
        env:
          ALLOWED_EXTENSIONS: ${{ secrets.ALLOWED_EXTENSIONS }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}

      - name: Run tests with pytest
        run: |
          mkdir -p ./test-reports
          pytest --disable-warnings --maxfail=1 --junitxml=./test-reports/results.xml
